### ISSUE TITLE
Xbox app now not letting me stream in very high and the start.bat isnt working!!!

### ISSUE THREAD

**Issue by ghost** [kaczorws/xboxappmod#11]
Hey kaczorws. I've had a problem with the xbox app mod you made. Now the start.bat wont work and now my xbox console companion wont let me stream in anything but the 'high' graphics setting. The 'very high' setting is completely gone. My stream looks terrible now. Can you help or do you have any upto date mods. 

Here's a couple of photos of whats going on with start.bat and powershell. 

You mod was working perfectly fine until a little while ago. Can you help?

From Perbliss
![Set execution policy error](https://user-images.githubusercontent.com/77074754/105957058-99809a80-60c8-11eb-942a-34ec8b33fd6a.png)
![xbox mod ap problems](https://user-images.githubusercontent.com/77074754/105957067-9b4a5e00-60c8-11eb-8975-00879989cafb.png)

**Comment by kaczorws** [comment]
Hi!

In the first screenshot it seems that you have entered "Y" twice - the first time when you confirmed Unrestricted policy and then a second time after that, so PowerShell does not recognize single "Y" character as a command, hence the error. Note that changing PowerShell execution policy needs to be done only once and then it should stay permanent on your system.

As for the second screenshot it seems that Xbox App settings file is corrupted or missing completely - this sometimes happens if for example you close the script before the Xbox App closes. However, it should be recreated once you run the Xbox App without the script. Unless the app is blocked using the hosts file, that is.

So the first thing you need to check is the hosts file - look for this entry:

`127.0.0.1 settings.data.microsoft.com`

If it's there, remove it and then run Xbox App without the script. The settings file should be recreated. After that close the Xbox App and run start.bat. It should start again but Very High settings should be available now.

Let me know if this helps.

**Comment by ghost** [comment]
Yeah I have been pressing 'Y' only once. Just n u as t have been a typo on the screenshot. I deleted the old files and redownloaded the xbox app mod. Ill find the hosfs file and delete it. I suspect maybe Microsoft are blocking the xbox app mod from working or the console companion got updated and messed with the configuration. 
How do you get to the hosts file? Do you have a pathway?
Sent from Yahoo Mail on Android 
 
  On Tue, 2 Feb 2021 at 2:06 pm, Pawel<notifications@github.com> wrote:   


Hi!

In the first screenshot it seems that you have entered "Y" twice - the first time when you confirmed Unrestricted policy and then a second time after that, so PowerShell does not recognize single "Y" character as a command, hence the error. Note that changing PowerShell execution policy needs to be done only once and then it should stay permanent on your system.

As for the second screenshot it seems that Xbox App settings file is corrupted or missing completely - this sometimes happens if for example you close the script before the Xbox App closes. However, it should be recreated once you run the Xbox App without the script. Unless the app is blocked using the hosts file, that is.

So the first thing you need to check is the hosts file - look for this entry:

127.0.0.1 settings.data.microsoft.com

If it's there, remove it and then run Xbox App without the script. The settings file should be recreated. After that close the Xbox App and run start.bat. It should start again but Very High settings should be available now.

Let me know if this helps.

**Comment by kaczorws** [comment]
Location of hosts file in Windows is:

`%SystemRoot%\system32\drivers\etc\`

So by default that would be:

`C:\WINDOWS\system32\drivers\etc`

**Comment by ghost** [comment]
I deleted the hosts file and now I can stream in very high again. Thanks for the support .ate. 

Sent from Yahoo Mail on Android 
 
  On Tue, 2 Feb 2021 at 4:08 pm, Pawel<notifications@github.com> wrote:   


Location of hosts file in Windows is:

%SystemRoot%\system32\drivers\etc\

So by default that would be:

C:\WINDOWS\system32\drivers\etc

**Comment by kaczorws** [comment]
Just remember to only remove that one entry from hosts file and not the whole hosts file itself.

`127.0.0.1 settings.data.microsoft.com`
