### ISSUE TITLE
Xbox Series S (not in Local Network) Info

### ISSUE THREAD

**Issue by Master-Antonio** [kaczorws/xboxappmod#17]
Work for the new xbox app?
Im streaming Xbox Series S and the quality is so low.
I have a gigabit, but i use the xbox series s from another network, not local network, and i play in monitor 1440p.
Its possible change the resolution to 1440p and use a big bitrate?

`<hostsblocker>127.0.0.1 settings.data.microsoft.com</hostsblocker>`
i have always use 127.0.0.1 or i have change it with the public ip of xbox?

Its possible change to 1440?
```
<!-- Desired resolution setting (480/720/1080) -->
	<resolution>1080</resolution>
```

Its possible go over 90?
```
<!-- Desired quality setting (10-90) -->
	<quality>90</quality>
```

**Comment by kaczorws** [comment]
Hi, as I pointed out in https://github.com/kaczorws/xboxappmod/issues/16#issuecomment-912524753 the script is not currently working because Microsoft has changed the domain from which the settings are downloaded (previously it was `settings.data.microsoft.com`) and I haven't yet figured out which one is the correct. Please find the post from the link for a list of all possible domains and you can test for yourself which one is the correct one but beware it's a very long list.

I do not own the Series S/X so can't really tell if it's working with these models or not.

It is not possible to change to 1440 as setting higher than 1080 always reverted to 480p. Also it is not recommended to go over 90 in quality as this started to produce graphical glitches, probably due to bitrate being to high.

**Comment by kaczorws** [comment]
This script is no longer maintained - worked only on old pre-2021 Xbox App (which supported only Xbox One/One S/One X).
