### ISSUE TITLE
Not working on v 48.62.6002

### ISSUE THREAD

**Issue by Bambi308** [kaczorws/xboxappmod#7]
Hi,

I used to play with Xbox Companion with the Very High option available. There were an update a few days ago and this option disappeared with a significant quality loss. I changed some values in settings.json before this update, but it seems that this file doesn't exist anymore.
I found your script but as it is based on the settings.json file, it cannot work because this file can't be found in LocalState.

![xbox_issue](https://user-images.githubusercontent.com/63092101/78333485-2e3e6880-758a-11ea-94a0-dc78e33fd75b.jpg)

Do you have an idea to upgrade your script and change the values elsewhere ? I don't find any 'GAME_STREAMING_VERY_HIGH_QUALITY_SETTINGS' string anymore in any file.

Great work, hope you have any idea for that!

**Comment by george-perry-radiant** [comment]
Yeah it doesn't seem to work anymore

**Comment by kaczorws** [comment]
Hello,

I just checked on my PC - I have the same version (48.62.6002.00000) and streaming using my script is working without any issues. I also checked LocalState directory and Settings.json file is there, so it seems that nothing changed from Xbox App side. I remember that messing with the settings file sometimes causes Xbox App to remove it (because it thinks it's broken) but it should re-download it, unless you blocked "settings.data.microsoft.com" address in your hosts file (using my script for example).

You can try to reinstall Xbox App and it should download Settings.json file, but first check if your hosts file does NOT contain line "127.0.0.1 settings.data.microsoft.com".

**Comment by Bambi308** [comment]
Hello kaczorws,

You are right, I added the line : 
127.0.0.1   settings.data.microsoft.com
to my hosts file to use the script.

Thank you very much, I have the file now that I can modify!
